### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ghost** [djblue/mini-pascal#3]
- [x] update exit point to follow chain of dummy nodes if needed
- [x] remove dummy nodes
- [ ] evaluation of constant expressions
- [ ] build extended blocks
- [ ] value numbering
- [ ] global redundancy?
  optional
- [ ] refactor

**Comment by djblue** [comment]
I think this list is complete. I will look into removing dummy nodes.

**Comment by ghost** [comment]
okay, i'll grab the exit point and maybe building extended blocks. lemme know if you run into issues with removing dummy nodes

**Comment by djblue** [comment]
I am going to try the value numbering stuff.
